include $(THEOS)/makefiles/common.mk

TWEAK_NAME = cmdLooper
cmdLooper_FILES = cmdLooper.xm
cmdLooper_FRAMEWORKS = UIKit
cmdLooper_CFLAGS = -fobjc-arc

include $(THEOS)/makefiles/tweak.mk
include $(THEOS)/makefiles/aggregate.mk